########################### ANAND'S ENVIRONMENT
# Here are my 4 Docker Hosts:
# - Home Server (hs) - Proxmox Unprivileged LXC with Ubuntu Server 22.04
# - Media / Database Server (mds) - Proxmox Unprivileged LXC with Ubuntu Server 22.04
# - Web Server (ws-arm) - Oracle Cloud Ampere A1 VPS with Ubuntu Server 24.04 (arm)
# - Synology (ds918) - Synology DS918+ DSM 7.X

########################### THIS COMPOSE FILE
# - Media / Database Server (mds) - Proxmox LXC with Ubuntu Server 22.04
# - Built using Deployrr
# - Docker version 28.3.2, build 578ccf6
# - Docker Compose version v2.38.2

########################### NETWORKS
# You may customize the network subnets (192.168.x.0/24) below as you please.
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  # NETWORKS-PLACEHOLDER-DO-NOT-DELETE

########################### SECRET
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
  mysql_root_password:
    file: $DOCKERDIR/secrets/mysql_root_password
  pgsql_teslamate_passwd:
    file: $DOCKERDIR/secrets/pgsql_teslamate_passwd
  # SECRETS-PLACEHOLDER-DO-NOT-DELETE

include:
  ########################### SERVICES
  # HOSTNAME defined in .env file
  - compose/$HOSTNAME/plex.yml
  - compose/$HOSTNAME/airsonic-advanced.yml
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/docker-gc.yml
  - compose/$HOSTNAME/influxdb.yml
  - compose/$HOSTNAME/mariadb.yml
  - compose/$HOSTNAME/jellyfin.yml 
  # # - compose/$HOSTNAME/plex-image-cleanup.yml
  # # - compose/$HOSTNAME/plex-meta-manager.yml
  - compose/$HOSTNAME/tautulli.yml
  - compose/$HOSTNAME/prometheus.yml
  # - compose/$HOSTNAME/pgsql-teslamate.yml
  # - compose/$HOSTNAME/node-exporter.yml
  # - compose/$HOSTNAME/mosquitto.yml
  # SERVICE-PLACEHOLDER-DO-NOT-DELETE



