http:
  middlewares:
    middlewares-oauth:
      forwardAuth:
        address: "http://oauth:4181/portals/main" 
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"
          - "X-Forwarded-Displayname"
          - "X-Authenticated-User"